# Dot-sourceable helper: New-HiddenTaskAction
#
# Registers a scheduled-task action that runs a command through wscript so its console is
# created with SW_HIDE and never pops a window (a plain `-WindowStyle Hidden` hides only
# AFTER the console has appeared, so a repeating task still flashes and steals focus).
#
# WScript.Shell.Run(cmd, 0, True) creates the process hidden, waits for it, and returns its
# exit code, so Task Scheduler's Last Run Result and ExecutionTimeLimit keep their meaning.
#
# Returns a CimInstance action suitable for Register-ScheduledTask -Action.
function New-HiddenTaskAction {
    param(
        [Parameter(Mandatory)][string]$Execute,
        [string]$Argument,
        [string]$WorkingDirectory,
        [Parameter(Mandatory)][string]$TaskName,
        [string]$WrapperDir
    )
    if (-not $WrapperDir) { $WrapperDir = Join-Path $PSScriptRoot 'hidden-tasks' }
    New-Item -ItemType Directory -Force -Path $WrapperDir | Out-Null
    $cmd = if ($Argument) { '"{0}" {1}' -f $Execute, $Argument } else { '"{0}"' -f $Execute }
    $safe = $TaskName -replace '[^\w\-]', '_'
    $vbs = Join-Path $WrapperDir "$safe.vbs"
    $esc = $cmd.Replace('"', '""')
    $lines = @(
        "' Generated by HiddenTaskAction.ps1 - hidden launcher for task '$TaskName'.",
        'Set sh = CreateObject("WScript.Shell")'
    )
    if ($WorkingDirectory) { $lines += "sh.CurrentDirectory = `"$($WorkingDirectory.Replace('"','""'))`"" }
    $lines += "WScript.Quit sh.Run(`"$esc`", 0, True)"
    [System.IO.File]::WriteAllText($vbs, ($lines -join "`r`n") + "`r`n", (New-Object System.Text.UTF8Encoding($false)))
    $wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'
    return New-ScheduledTaskAction -Execute $wscript -Argument ('//B //NoLogo "{0}"' -f $vbs)
}
