# install-engine-vitals-task.ps1 - register (or remove) the 'DSH Engine Vitals' task.
#
# WHY THIS FILE EXISTS RATHER THAN JUST A .vbs
#
# The hidden VBS launchers live in `scripts/hidden-tasks/`, which is gitignored
# because they are generated per machine. Registering the task by hand therefore
# reached exactly one machine, and the fix for "the engine died and nothing said
# so" would have protected only the laptop it was written on. This installer is
# the versioned half: it writes the launcher and registers the task, so any
# machine with this repo can have the same instrument.
#
# WHAT IT REGISTERS
#   A task that runs scripts/engine-vitals.mjs every -IntervalMinutes and exits
#   0 (clean) / 1 (warning) / 3 (engine unreachable). The task's LastTaskResult
#   is therefore a readable health signal: `Get-ScheduledTaskInfo`.
#
# USAGE
#   pwsh -File scripts/install-engine-vitals-task.ps1
#   pwsh -File scripts/install-engine-vitals-task.ps1 -IntervalMinutes 10
#   pwsh -File scripts/install-engine-vitals-task.ps1 -Uninstall
#
# It is idempotent: re-running replaces the task.

[CmdletBinding()]
param(
    [string] $TaskName = 'DSH Engine Vitals (5m)',
    [int]    $IntervalMinutes = 5,
    [switch] $Uninstall
)

$ErrorActionPreference = 'Stop'

if ($Uninstall) {
    $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "removed task '$TaskName'"
    } else {
        Write-Host "task '$TaskName' was not registered"
    }
    return
}

if ($IntervalMinutes -lt 1) { throw 'IntervalMinutes must be at least 1' }

$repoRoot = Split-Path -Parent $PSScriptRoot
$script   = Join-Path $repoRoot 'scripts\engine-vitals.mjs'
if (-not (Test-Path -LiteralPath $script)) { throw "engine-vitals.mjs not found at $script" }

$node = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $node) { throw 'node not found on PATH; the task runs engine-vitals.mjs with node' }
$wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'

# The hidden launcher, written the same way the other DSH tasks are: wscript runs
# the command with a hidden window (0) and waits (True), so no console flashes and
# no orphan child outlives the task.
$launcherDir = Join-Path $PSScriptRoot 'hidden-tasks'
if (-not (Test-Path -LiteralPath $launcherDir)) { New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null }
$launcher = Join-Path $launcherDir (($TaskName -replace '[^A-Za-z0-9]+', '_') + '.vbs')
$vbs = @"
' Generated by install-engine-vitals-task.ps1 - hidden launcher for task '$TaskName'.
' Runs engine-vitals.mjs: one CSV row every $IntervalMinutes minutes, and an entry in
' ~/.dsh/metrics/engine-vitals.log only when the engine restarted, a warning is new,
' or 6 hours have passed. Exit 0 clean / 1 warning / 3 engine unreachable.
Set sh = CreateObject("WScript.Shell")
WScript.Quit sh.Run("""$node"" ""$script""", 0, True)
"@
Set-Content -LiteralPath $launcher -Value $vbs -Encoding ASCII
Write-Host "launcher: $launcher"

$action = New-ScheduledTaskAction -Execute $wscript -Argument "//B //NoLogo `"$launcher`""
# Indefinite repetition: -RepetitionDuration is deliberately omitted. [TimeSpan]::MaxValue
# is out of range for the task XML ("Duration:P99999999DT23H59M59S" is rejected), and the
# existing 'DSH Engine Watchdog (1m)' omits it for the same reason.
#
# The parentheses around the -At expression are load-bearing: `-At (Get-Date).AddMinutes 1`
# is parsed as an argument list containing the METHOD rather than its result, and throws
# "Cannot convert ... PSMethod ... to type System.DateTime". That bug shipped once here and
# left the task unregistered, because the unregister above it had already succeeded.
$trigger = New-ScheduledTaskTrigger -Once -At ((Get-Date).AddMinutes(1)) `
    -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes)
$principal = New-ScheduledTaskPrincipal -UserId "$env:USERDOMAIN\$env:USERNAME" `
    -LogonType Interactive -RunLevel Limited
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes ([Math]::Max(2, $IntervalMinutes - 1)))

# -Force replaces an existing task in one step. An explicit Unregister-ScheduledTask
# FIRST would be a hazard, not tidiness: it opens a window in which no task exists, and a
# later failure (the -At bug above did exactly this) leaves the machine with no instrument
# at all. Verified by the uninstall/reinstall round trip in the header comment.
Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Principal $principal -Settings $settings -Force | Out-Null

$t = Get-ScheduledTask -TaskName $TaskName
Write-Host "registered '$TaskName' state=$($t.State) every $IntervalMinutes min"
Write-Host "verify with: Get-ScheduledTaskInfo -TaskName '$TaskName'"
Write-Host "read the incident log: ~/.dsh/metrics/engine-vitals.log"
