# install-engine-vitals-task.ps1 - register (or remove) the 'DSH Engine Vitals' task.
#
# WHY THIS FILE EXISTS RATHER THAN JUST A .vbs
#
# The hidden VBS launchers live in `scripts/hidden-tasks/`, which is gitignored
# because they are generated per machine. Registering the task by hand therefore
# reached exactly one machine, and the fix for "the engine died and nothing said
# so" would have protected only the laptop it was written on. This installer is
# the versioned half: it writes the launcher and registers the task, so any
# machine with this repo can have the same instrument.
#
# WHAT IT REGISTERS
#   A task that runs scripts/engine-vitals.mjs every -IntervalMinutes and exits
#   0 (clean) / 1 (warning) / 3 (engine unreachable). The task's LastTaskResult
#   is therefore a readable health signal: `Get-ScheduledTaskInfo`.
#
# USAGE
#   pwsh -File scripts/install-engine-vitals-task.ps1
#   pwsh -File scripts/install-engine-vitals-task.ps1 -IntervalMinutes 10
#   pwsh -File scripts/install-engine-vitals-task.ps1 -Uninstall
#
# It is idempotent: re-running replaces the task.

[CmdletBinding()]
param(
    [string] $TaskName = 'DSH Engine Vitals (5m)',
    [int]    $IntervalMinutes = 5,
    # S4U by default: runs whether or not the user is logged on (see the note at the principal).
    [ValidateSet('S4U', 'Interactive', 'Password')]
    [string] $LogonType = 'S4U',
    [switch] $Uninstall,
    [switch] $RunNow
)

$ErrorActionPreference = 'Stop'

if ($Uninstall) {
    $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "removed task '$TaskName'"
    } else {
        Write-Host "task '$TaskName' was not registered"
    }
    return
}

if ($IntervalMinutes -lt 1) { throw 'IntervalMinutes must be at least 1' }

$repoRoot = Split-Path -Parent $PSScriptRoot
$script   = Join-Path $repoRoot 'scripts\engine-vitals.mjs'
if (-not (Test-Path -LiteralPath $script)) { throw "engine-vitals.mjs not found at $script" }

$node = (Get-Command node -ErrorAction SilentlyContinue).Source
if (-not $node) { throw 'node not found on PATH; the task runs engine-vitals.mjs with node' }
$wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'

# The hidden launcher, written the same way the other DSH tasks are: wscript runs
# the command with a hidden window (0) and waits (True), so no console flashes and
# no orphan child outlives the task.
$launcherDir = Join-Path $PSScriptRoot 'hidden-tasks'
if (-not (Test-Path -LiteralPath $launcherDir)) { New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null }
$launcher = Join-Path $launcherDir (($TaskName -replace '[^A-Za-z0-9]+', '_') + '.vbs')
$vbs = @"
' Generated by install-engine-vitals-task.ps1 - hidden launcher for task '$TaskName'.
' Runs engine-vitals.mjs: one CSV row every $IntervalMinutes minutes, and an entry in
' ~/.dsh/metrics/engine-vitals.log only when the engine restarted, a warning is new,
' or 6 hours have passed. Exit 0 clean / 1 warning / 3 engine unreachable.
Set sh = CreateObject("WScript.Shell")
WScript.Quit sh.Run("""$node"" ""$script""", 0, True)
"@
Set-Content -LiteralPath $launcher -Value $vbs -Encoding ASCII
Write-Host "launcher: $launcher"

$action = New-ScheduledTaskAction -Execute $wscript -Argument "//B //NoLogo `"$launcher`""
# Indefinite repetition: -RepetitionDuration is deliberately omitted. [TimeSpan]::MaxValue
# is out of range for the task XML ("Duration:P99999999DT23H59M59S" is rejected), and the
# existing 'DSH Engine Watchdog (1m)' omits it for the same reason.
#
# The parentheses around the -At expression are load-bearing: `-At (Get-Date).AddMinutes 1`
# is parsed as an argument list containing the METHOD rather than its result, and throws
# "Cannot convert ... PSMethod ... to type System.DateTime". That bug shipped once here and
# left the task unregistered, because the unregister above it had already succeeded.
#
# AND THE VALUE IS IN THE PAST, DELIBERATELY. A `-Once` trigger starting in the future leaves the
# task Queued, and Start-ScheduledTask on a queued task is a NO-OP -- so the task never runs and
# LastTaskResult stays 267011 (SCHED_S_TASK_HAS_NOT_RUN). Measured on ZABZ-TECH 2026-09-28: both
# instruments registered "successfully" and neither had ever executed. That is L174's trap.
$trigger = New-ScheduledTaskTrigger -Once -At ((Get-Date).AddMinutes(-1)) `
    -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes)
# ALWAYS the process identity -- never "$env:USERDOMAIN\$env:USERNAME".
# Measured on ZABZ-TECH over ssh, 2026-09-28: USERDOMAIN=WORKGROUP and USERNAME=ezabz, so the
# env-var form builds "WORKGROUP\ezabz", an account that does not exist, and Register-ScheduledTask
# fails with "No mapping between account names and security IDs was done". Meanwhile
# WindowsIdentity.GetCurrent().Name is "zabz-tech\ezabz" and translates to a valid SID. A fallback
# on emptiness is not enough: the variables were present and wrong.
#
# LOGON TYPE S4U BY DEFAULT, AND THAT IS THE WHOLE POINT. An Interactive-logon task only runs while
# that user is logged on at the console. ZABZ-TECH is an office machine with nobody logged on
# (`qwinsta` showed `console 1 Conn` and NO USERNAME), so the identical installer that works on
# ZABZ-YOGA produced tasks reporting 267011 (SCHED_S_TASK_HAS_NOT_RUN) forever -- measured
# 2026-09-28. An instrument that is inert exactly when nobody is present is worthless: that is when
# a silent engine outage goes unnoticed. S4U needs no stored password and runs regardless.
$identity = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
$principal = New-ScheduledTaskPrincipal -UserId $identity `
    -LogonType $LogonType -RunLevel Limited
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes ([Math]::Max(2, $IntervalMinutes - 1)))

# -Force replaces an existing task in one step. An explicit Unregister-ScheduledTask
# FIRST would be a hazard, not tidiness: it opens a window in which no task exists, and a
# later failure (the -At bug above did exactly this) leaves the machine with no instrument
# at all. Verified by the uninstall/reinstall round trip in the header comment.
Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Principal $principal -Settings $settings -Force | Out-Null

$t = Get-ScheduledTask -TaskName $TaskName
Write-Host "registered '$TaskName' state=$($t.State) every $IntervalMinutes min"

# -RunNow exists so a deployment can be VERIFIED rather than assumed. Registering a task proves
# only that a definition exists; this repo has already been bitten by a task that reported success
# and did nothing (L174), so the installer can drive one pass and print its result.
if ($RunNow) {
    Start-ScheduledTask -TaskName $TaskName
    Start-Sleep -Seconds 20
    $i = Get-ScheduledTaskInfo -TaskName $TaskName
    Write-Host "ran once: last=$($i.LastRunTime) result=$($i.LastTaskResult)  (0 clean / 1 warning / 3 engine unreachable)"
}
Write-Host "verify with: Get-ScheduledTaskInfo -TaskName '$TaskName'"
Write-Host "read the incident log: ~/.dsh/metrics/engine-vitals.log"
