# install-profile-gate-task.ps1 - register a PERIODIC boot-gate check on this machine.
#
# WHY. On 2026-09-17 a bundle name that stops an engine booting was repaired on the three machines
# the repairing session could see. Yocheved's laptop was not on that list; it rebooted on 09-18 and
# could not start its engine FOR TEN DAYS, and nothing said so -- the logon task returned 0 while
# the engine died in under a second (L2609). `profile-gate.mjs` is the check that catches that
# class, but a check nobody runs is the same as no check. This registers it.
#
# It does NOT need a working engine: `dsh --profile <p> --dump-config` composes the layers, starts
# nothing, and is a one-shot node process -- so it still runs on the machine whose engine is dead,
# which is the entire point.
#
# OUTPUT, AND WHY IT IS NOT JUST THE EXIT CODE
#   * the task's LastTaskResult carries 0 (all profiles compose) / 1 (CANNOT BOOT) / 3 (the gate
#     could not exercise a harness -- a REFUSAL, not a verdict);
#   * on failure the gate appends to <DSH_HOME>/metrics/profile-gate.log, at most once per 24h, so
#     the condition is visible to a human without opening Task Scheduler. A periodic check whose
#     only signal is a task result reproduces the exact failure it was built to catch.
#
# ASCII ONLY, deliberately: this file is also delivered to machines through channels that corrupt
# non-ASCII bytes (an em-dash became mojibake and broke a remote PowerShell parse on 2026-09-28).
#
# USAGE
#   pwsh -File scripts/install-profile-gate-task.ps1
#   pwsh -File scripts/install-profile-gate-task.ps1 -IntervalMinutes 30
#   pwsh -File scripts/install-profile-gate-task.ps1 -DshHome C:\Users\cheve\.dsh
#   pwsh -File scripts/install-profile-gate-task.ps1 -Uninstall
#
# Idempotent: re-running replaces the task in one step (-Force), never by unregister-then-register,
# because that leaves a window with no check at all and a later failure strands the machine.

[CmdletBinding()]
param(
    [string] $TaskName = 'DSH Profile Gate (15m)',
    [int]    $IntervalMinutes = 15,
    [string] $DshHome,
    [string] $Node,
    # S4U by default: runs whether or not the user is logged on (see the note at the principal).
    [ValidateSet('S4U', 'Interactive', 'Password')]
    [string] $LogonType = 'S4U',
    [switch] $Uninstall,
    [switch] $RunNow
)

$ErrorActionPreference = 'Stop'

if ($Uninstall) {
    $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "removed task '$TaskName'"
    } else { Write-Host "task '$TaskName' was not registered" }
    return
}

if ($IntervalMinutes -lt 1) { throw 'IntervalMinutes must be at least 1' }

$gate = Join-Path $PSScriptRoot 'profile-gate.mjs'
if (-not (Test-Path -LiteralPath $gate)) { throw "profile-gate.mjs not found beside this script ($gate)" }

if (-not $Node) {
    $Node = (Get-Command node -ErrorAction SilentlyContinue).Source
    if (-not $Node) { throw 'node not found on PATH; pass -Node <path to node.exe>' }
}

$launcherDir = Join-Path $PSScriptRoot 'hidden-tasks'
if (-not (Test-Path -LiteralPath $launcherDir)) { New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null }
$stem = ($TaskName -replace '[^A-Za-z0-9]+', '_')

# A cmd wrapper carries DSH_HOME when the task's account is not the user whose home holds the
# profiles (the exec API on her laptop runs as SYSTEM, so os.homedir() would be the SYSTEM profile
# and the gate would enumerate nothing). Plain node with no wrapper otherwise.
$cmdPath = Join-Path $launcherDir "$stem.cmd"
if ($DshHome) {
    $lines = @(
        '@echo off',
        'rem Generated by install-profile-gate-task.ps1 - do not edit by hand.',
        "set `"DSH_HOME=$DshHome`"",
        "`"$Node`" `"$gate`""
    )
} else {
    $lines = @(
        '@echo off',
        'rem Generated by install-profile-gate-task.ps1 - do not edit by hand.',
        "`"$Node`" `"$gate`""
    )
}
Set-Content -LiteralPath $cmdPath -Value $lines -Encoding ASCII
Write-Host "wrapper : $cmdPath"

$vbsPath = Join-Path $launcherDir "$stem.vbs"
$vbs = @"
' Generated by install-profile-gate-task.ps1 - hidden launcher for task '$TaskName'.
' Runs the boot gate: composes every dsh profile without starting an engine. Exit 0 all compose,
' 1 CANNOT BOOT, 3 the gate could not exercise a harness (a refusal, not a verdict).
Set sh = CreateObject("WScript.Shell")
WScript.Quit sh.Run("cmd.exe /c """"$cmdPath""""", 0, True)
"@
Set-Content -LiteralPath $vbsPath -Value $vbs -Encoding ASCII
Write-Host "launcher: $vbsPath"

$action = New-ScheduledTaskAction -Execute (Join-Path $env:SystemRoot 'System32\wscript.exe') -Argument "//B //NoLogo `"$vbsPath`""
# Indefinite repetition: -RepetitionDuration is omitted on purpose. [TimeSpan]::MaxValue is out of
# range for the task XML, and omitting it gives an unbounded repetition.
#
# -At IS IN THE PAST, DELIBERATELY. A `-Once` trigger whose start time is in the future leaves the
# task in state Queued, and Start-ScheduledTask on a queued task is a NO-OP -- so the task silently
# never runs and LastTaskResult stays 267011 (SCHED_S_TASK_HAS_NOT_RUN). That is L174's trap, and it
# cost a deployment round on ZABZ-TECH on 2026-09-28: both instruments registered "successfully" and
# neither had ever executed. A past start makes it run at once and then on the interval.
$trigger = New-ScheduledTaskTrigger -Once -At ((Get-Date).AddMinutes(-1)) `
    -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes)
# ALWAYS the process identity -- never "$env:USERDOMAIN\$env:USERNAME".
# Measured on ZABZ-TECH over ssh, 2026-09-28: USERDOMAIN=WORKGROUP and USERNAME=ezabz, so the
# env-var form builds "WORKGROUP\ezabz", an account that does not exist, and Register-ScheduledTask
# fails with "No mapping between account names and security IDs was done". Meanwhile
# WindowsIdentity.GetCurrent().Name is "zabz-tech\ezabz" and translates to a valid SID. A fallback
# on emptiness is not enough: the variables were present and wrong.
#
# LOGON TYPE S4U BY DEFAULT, AND THAT IS THE WHOLE POINT. An Interactive-logon task only runs while
# that user is logged on at the console. ZABZ-TECH is an office machine and nobody is logged into
# it, so the identical installer that works on ZABZ-YOGA produced tasks that reported
# 267011 (SCHED_S_TASK_HAS_NOT_RUN) forever -- measured 2026-09-28, with `qwinsta` showing
# `console 1 Conn` and NO USERNAME. An instrument that is inert exactly when nobody is present is
# worthless: that is when a silent engine outage goes unnoticed. S4U runs whether or not the user
# is logged on and needs no stored password. These checks are headless, so they lose nothing.
$identity = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
$principal = New-ScheduledTaskPrincipal -UserId $identity `
    -LogonType $LogonType -RunLevel Limited
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes 10)

Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Principal $principal -Settings $settings -Force | Out-Null

$t = Get-ScheduledTask -TaskName $TaskName
Write-Host "registered '$TaskName' state=$($t.State) every $IntervalMinutes min"

if ($RunNow) {
    Start-ScheduledTask -TaskName $TaskName
    Start-Sleep -Seconds 15
    $i = Get-ScheduledTaskInfo -TaskName $TaskName
    Write-Host "ran once: last=$($i.LastRunTime) result=$($i.LastTaskResult)  (0 compose / 1 CANNOT BOOT / 3 refusal)"
}
$logHome = if ($DshHome) { $DshHome } else { Join-Path $env:USERPROFILE '.dsh' }
Write-Host "the gate's incident log (written only on failure): $logHome\metrics\profile-gate.log"
