# install-mcp-health-task.ps1 - register (or remove) the 'DSH MCP Health' task.
#
# WHY THIS FILE EXISTS RATHER THAN JUST A .vbs
#
# Same reason as install-engine-vitals-task.ps1: the hidden VBS launchers live in
# `scripts/hidden-tasks/`, which is gitignored because they are generated per machine.
# Registering a task by hand reaches exactly one machine. This installer is the versioned
# half, so any machine with this repo can have the same instrument.
#
# WHAT IT REGISTERS
#   A task that runs scripts/mcp-health.ps1 every -IntervalMinutes. That script reads the
#   engine's own stderr log (the launcher redirects it to
#   <logDir>/3099-<stamp>.err.log) and looks for dsh-mcp-client's give-up line. Exit 0 means
#   no give-up on record; exit 1 means a RUNNING engine has a give-up on record, so its tool
#   set is unregistered and will not come back without a restart; exit 2 means the engine or
#   its log could not be read. 2 is never a pass.
#
#   The task's LastTaskResult is therefore a readable health signal:
#     Get-ScheduledTaskInfo -TaskName 'DSH MCP Health (5m)'
#   and the structured record is at ~/.dsh-mcp-health/status.json
#   (same idiom as ~/.dsh-sync-status/status.json), with a one-line-per-run history beside it.
#
# WHY 5 MINUTES
#   The budget that must expire before a give-up happens is ~27.5 minutes (reconnect:
#   maxAttempts 60, maxDelayMs 30000 on every MCP row). A 5-minute cadence means the state
#   is on record within 5 minutes of it becoming true, which is far inside the window in
#   which a person could still care. It costs one short read every 5 minutes.
#
# USAGE
#   pwsh -File scripts/install-mcp-health-task.ps1
#   pwsh -File scripts/install-mcp-health-task.ps1 -IntervalMinutes 15
#   pwsh -File scripts/install-mcp-health-task.ps1 -RunNow     # register and drive one pass
#   pwsh -File scripts/install-mcp-health-task.ps1 -Uninstall
#
# It is idempotent: re-running replaces the task.

[CmdletBinding()]
param(
    [string] $TaskName = 'DSH MCP Health (5m)',
    [int]    $IntervalMinutes = 5,
    # Interactive is the DEFAULT HERE, not S4U, and that is a measured choice rather than a
    # preference. Registering with -LogonType S4U from a non-elevated shell fails with
    # "Access is denied" on ZABZ-YOGA (measured 2026-10-02): this harness runs unelevated, and
    # dshw.ps1's own notes say such a token "CANNOT re-register" a task owned by the elevated
    # context that created the existing DSH tasks. Registering the same definition with
    # Interactive + the current user SUCCEEDS unelevated -- probed directly, then used to
    # register this task. Use -LogonType S4U only from an elevated shell, and only if the task
    # must run with nobody logged on; on a workstation the owner works at, Interactive is the
    # honest scope because that is when he can actually see a missing tool set.
    [ValidateSet('S4U', 'Interactive', 'Password')]
    [string] $LogonType = 'Interactive',
    [switch] $Uninstall,
    [switch] $RunNow
)

$ErrorActionPreference = 'Stop'

if ($Uninstall) {
    $existing = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
    if ($existing) {
        Unregister-ScheduledTask -TaskName $TaskName -Confirm:$false
        Write-Host "removed task '$TaskName'"
    } else {
        Write-Host "task '$TaskName' was not registered"
    }
    return
}

if ($IntervalMinutes -lt 1) { throw 'IntervalMinutes must be at least 1' }

$repoRoot = Split-Path -Parent $PSScriptRoot
$script   = Join-Path $repoRoot 'scripts\mcp-health.ps1'
if (-not (Test-Path -LiteralPath $script)) { throw "mcp-health.ps1 not found at $script" }

$pwsh = (Get-Command pwsh -ErrorAction SilentlyContinue).Source
if (-not $pwsh) { $pwsh = Join-Path $env:ProgramFiles 'PowerShell\7\pwsh.exe' }
if (-not (Test-Path -LiteralPath $pwsh)) { throw "pwsh not found; the detector is a PowerShell script" }
$wscript = Join-Path $env:SystemRoot 'System32\wscript.exe'

# The hidden launcher, written the way the other DSH tasks are: wscript runs the command
# with a hidden window (0) and waits (True), so no console flashes and no orphan child
# outlives the task.
$launcherDir = Join-Path $PSScriptRoot 'hidden-tasks'
if (-not (Test-Path -LiteralPath $launcherDir)) { New-Item -ItemType Directory -Path $launcherDir -Force | Out-Null }
$launcher = Join-Path $launcherDir (($TaskName -replace '[^A-Za-z0-9]+', '_') + '.vbs')
$vbs = @"
' Generated by install-mcp-health-task.ps1 - hidden launcher for task '$TaskName'.
' Runs mcp-health.ps1: reads the engine's stderr log for the MCP give-up line and writes
' ~/.dsh-mcp-health/status.json. Exit 0 no give-up / 1 give-up on record / 2 cannot see.
Set sh = CreateObject("WScript.Shell")
WScript.Quit sh.Run("""$pwsh"" -NoLogo -NoProfile -NonInteractive -ExecutionPolicy Bypass -File ""$script""", 0, True)
"@
Set-Content -LiteralPath $launcher -Value $vbs -Encoding ASCII
Write-Host "launcher: $launcher"

$action = New-ScheduledTaskAction -Execute $wscript -Argument "//B //NoLogo `"$launcher`""

# Indefinite repetition: -RepetitionDuration is deliberately omitted, exactly as the other
# DSH tasks do, because [TimeSpan]::MaxValue is out of range for the task XML.
#
# The -At value is IN THE PAST on purpose. A -Once trigger starting in the future leaves the
# task Queued, and Start-ScheduledTask on a queued task is a NO-OP, so the task never runs and
# LastTaskResult stays 267011 forever. That trap is measured in this repo (L174) and it is why
# this installer can be asked to drive one pass and print the result.
$trigger = New-ScheduledTaskTrigger -Once -At ((Get-Date).AddMinutes(-1)) `
    -RepetitionInterval (New-TimeSpan -Minutes $IntervalMinutes)

# Always the process identity, never "$env:USERDOMAIN\$env:USERNAME": measured on a machine
# joined to WORKGROUP, the env-var form builds an account that does not exist and registration
# fails with "No mapping between account names and security IDs was done".
#
# S4U by default so the instrument runs with nobody logged on -- which is exactly when a
# silent tool-set loss would otherwise go unnoticed.
$identity = [System.Security.Principal.WindowsIdentity]::GetCurrent().Name
$principal = New-ScheduledTaskPrincipal -UserId $identity -LogonType $LogonType -RunLevel Limited
$settings = New-ScheduledTaskSettingsSet -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
    -MultipleInstances IgnoreNew -ExecutionTimeLimit (New-TimeSpan -Minutes ([Math]::Max(2, $IntervalMinutes - 1)))

# -Force replaces an existing task in one step. An explicit unregister first would open a
# window in which no instrument exists, and a later failure would leave the machine blind.
Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger $trigger `
    -Principal $principal -Settings $settings -Force | Out-Null

$t = Get-ScheduledTask -TaskName $TaskName
Write-Host "registered '$TaskName' state=$($t.State) every $IntervalMinutes min"

if ($RunNow) {
    Start-ScheduledTask -TaskName $TaskName
    Start-Sleep -Seconds 15
    $i = Get-ScheduledTaskInfo -TaskName $TaskName
    Write-Host "ran once: last=$($i.LastRunTime) result=$($i.LastTaskResult)  (0 no give-up / 1 give-up on record / 2 cannot see)"
}
Write-Host "verify with: Get-ScheduledTaskInfo -TaskName '$TaskName'"
Write-Host "read the record: ~/.dsh-mcp-health/status.json"
