/**
 * The spend guard: one daily counter, three money thresholds, one step refusal,
 * and one concurrency ceiling. Installed as its own host row
 * (`dsh-plugin-cost/guard`), beside `/cost`, sharing this package's single price
 * table.
 *
 * WHY IT IS IN THIS PACKAGE. The rate card (`pricing.json`), the fold
 * (`cost-core.mjs`) and the durable-log reader (`session-log.mjs`) already live
 * here and are already tested against real logs. A second price table or a
 * second fold is exactly the drift this system has been punished for twice, so
 * `lib/index.js` and `lib/guard.js` are both generated by `scripts/build.mjs`
 * from those same three sources: there is no second card to drift onto, only
 * regenerated output.
 *
 * HOW IT COUNTS. Two paths, and they are not equal:
 *
 *   LIVE — `session/event` on every `assistant/message` that carries a usage
 *   sample, priced at that event's own timestamp (the card is time-of-day, so
 *   the timestamp IS part of the price). This is this engine's own traffic,
 *   exactly as the engine recorded it: no decoding, no mtime filter, no disk
 *   scan in the path. **This is the number the ceiling is measured against.**
 *
 *   SEED — one read of `<DSH_HOME>/sessions` at activation, for events newer
 *   than the stored watermark, so a restart remembers the morning instead of
 *   forgetting it. It is a SCAN, and `docs/mesh/65-spend-guard.md` §2.2 measured
 *   what a scan is worth: on 2026-09-15 the local logs held 50 % of the misses
 *   and 76 % of the hits of this machine's own ledger line. So a scan can only
 *   ever LOWER the counter, never set it: **a scan seeds, the live stream
 *   decides.**
 *
 * HOW IT ENFORCES. `agent/pre-step` is a Cordis waterfall reached once per step,
 * before `this.session.append("step/start", …)` and therefore before any request
 * is billed (`dsh-agent-loop/lib/index.js:937-947`: a `{kind:'reject'}` sets
 * `turnEnds = {kind:'blocked'}` and returns before the request). A listener that
 * returns `{kind:'reject'}` without calling `next()` vetoes the step; a shipped
 * package already does exactly this shape (`dsh-hooks-claude-code/lib/index.js:239`).
 * The turn closes durably as `blocked`, the session stays resumable, and nothing
 * is destroyed — queue, never amputate.
 *
 * HOW IT FAILS. Never open on the money path:
 *
 *   * an UNPRICED route is charged at the dearest rate on the card, never zero,
 *     so a model id that changes under us cannot silently become free;
 *   * an INTERNAL error rejects the step (`onInternalError: 'closed'`), so the
 *     guard's own defect cannot become an unbounded spend;
 *   * a MISSING or zeroed price card refuses to mount and refuses to price, so
 *     the guard never pretends everything is $0.00;
 *   * an unreadable state file is treated as an unknown day and re-seeded from
 *     the logs, labelled a lower bound.
 *
 * HOW IT FAILS TO ACTIVATE. It does not. `lib/guard.js` resolves only `node:`
 * builtins while it is being IMPORTED — `@deepseek-ai/schemastery`, needed only
 * to register the settings namespace, is resolved lazily at mount, from several
 * candidate roots with shape validation, and a failure there is a reported
 * DEGRADED mode rather than an absent guard (`src/guard-entry.mjs` carries the
 * measurement that made this structural). Two surfaces say which mode is in
 * force: a `warn`-level line on the engine's own log, and
 * `<DSH_HOME>/health/spend-guard.json`, written at mount with `degraded`, the
 * attempts, and the effective limits. See `docs/2026-09-28-guard-activation.md`.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import { dshHome, readSessionLog } from './session-log.mjs';
import { PRICING, MICRO, indexRoutes, costOf, normalizeUsage } from './cost-core.mjs';

const DAY_MS = 86400000;

/**
 * Defaults. These are the protective values `docs/mesh/96-gateway-at-scale.md` §5
 * justifies from measurement, and every one of them is a one-line change in
 * `settings/base.yaml` or in the row's `config`.
 *
 * $35 / $80 / $150 is deliberately NOT the $25 / $35 / $50 that doc 65 first
 * proposed: $50 is 44 minutes of a 55-agent fleet at the measured $68/hour, and
 * a ceiling crossed in the first hour of normal work gets raised by accident.
 * Above $150 the design already knows what to do — refuse, block the turn,
 * resume tomorrow.
 */
const DEFAULTS = {
  warnUsd: 35,
  fanoutUsd: 80,
  ceilingUsd: 150,
  concurrencyCap: 12,
  onInternalError: 'closed', // 'closed' refuses the step; 'open' allows it and says so
  seedFromLogs: true,
  seedLookbackHours: 24,
  stateFile: '', // '' -> <dshHome>/spend-guard/day.json
  sessionsRoot: '', // '' -> <dshHome>/sessions
  healthFile: '', // '' -> <dshHome>/health/spend-guard.json — the activation record
};

/** The money limits, in USD. */
const MONEY_KEYS = ['warnUsd', 'fanoutUsd', 'ceilingUsd'];

/** Every key the guard understands; anything else is named and ignored. */
const KNOWN_KEYS = [...MONEY_KEYS, 'concurrencyCap', 'onInternalError', 'seedFromLogs', 'seedLookbackHours', 'stateFile', 'sessionsRoot', 'healthFile'];

/** Namespace of the shared settings block this guard owns. */
const SETTINGS_NAMESPACE = 'spend-guard';

/** True for a finite number that can be a money limit, an hour count or a cap. */
function isLimit(value) {
  return typeof value === 'number' && Number.isFinite(value) && value >= 0;
}

/**
 * Pick the effective limits from the composition row's `config`, which the
 * settings provider has already merged: schema defaults, then this row as the
 * `base` layer, then the user layer in `settings.yaml`. A profile with no
 * settings provider simply gets the row's config.
 * @param {object} config the composition entry's config
 * @returns {object} limits and switches with every default applied
 */
function resolveLimits(config) {
  const source = config === undefined || config === null ? {} : config;
  const out = {
    onInternalError: source.onInternalError === 'open' ? 'open' : DEFAULTS.onInternalError,
    seedFromLogs: source.seedFromLogs !== false,
    stateFile: typeof source.stateFile === 'string' ? source.stateFile : DEFAULTS.stateFile,
    sessionsRoot: typeof source.sessionsRoot === 'string' ? source.sessionsRoot : DEFAULTS.sessionsRoot,
    healthFile: typeof source.healthFile === 'string' ? source.healthFile : DEFAULTS.healthFile,
    concurrencyCap: Number.isInteger(source.concurrencyCap) && source.concurrencyCap >= 0 ? source.concurrencyCap : DEFAULTS.concurrencyCap,
    seedLookbackHours: isLimit(source.seedLookbackHours) ? source.seedLookbackHours : DEFAULTS.seedLookbackHours,
  };
  for (const key of MONEY_KEYS) out[key] = isLimit(source[key]) ? source[key] : DEFAULTS[key];
  // An unknown key must never silently disable a limit: it is reported instead.
  out.unknownKeys = Object.keys(source).filter((key) => KNOWN_KEYS.indexOf(key) === -1);
  return out;
}

/** Micro-USD limits derived from the dollar ones, for the counter comparison. */
function microLimits(limits) {
  return {
    warnMicro: Math.round(limits.warnUsd * MICRO),
    fanoutMicro: Math.round(limits.fanoutUsd * MICRO),
    ceilingMicro: Math.round(limits.ceilingUsd * MICRO),
  };
}

/** Start of the UTC day containing `ms`. The card's tiers are UTC, so the day is too. */
function utcDayStart(ms) {
  return Math.floor(ms / DAY_MS) * DAY_MS;
}

/**
 * The decision, as a pure function of the day's counter and the limits.
 *
 * `reject` on money wins over everything: past the hard ceiling nothing new
 * starts for any reason. `fanout` and `concurrency` are warnings, not vetoes —
 * a running turn is never interrupted, and the step is admitted with a notice.
 *
 * @param {number} dayMicro today's spend in micro-USD
 * @param {{warnMicro:number,fanoutMicro:number,ceilingMicro:number}} limits
 * @param {{generating:number,cap:number,selfGenerating:boolean}} [counts]
 * @returns {{verdict:'ok'|'warn'|'fanout'|'concurrency'|'reject',rejectReason:string,noticeClass:string}}
 */
function decide(dayMicro, limits, counts) {
  if (dayMicro >= limits.ceilingMicro) return { verdict: 'reject', rejectReason: 'daily ceiling', noticeClass: 'ceiling' };
  const cap = counts === undefined ? 0 : counts.cap;
  const generating = counts === undefined ? 0 : counts.generating;
  const self = counts === undefined ? false : counts.selfGenerating === true;
  if (cap > 0 && generating >= cap && !self) return { verdict: 'reject', rejectReason: 'concurrency cap', noticeClass: 'concurrency' };
  if (dayMicro >= limits.fanoutMicro) return { verdict: 'fanout', rejectReason: '', noticeClass: 'fanout' };
  if (cap > 0 && generating >= cap - 1 && !self) return { verdict: 'concurrency', rejectReason: '', noticeClass: 'concurrency' };
  if (dayMicro >= limits.warnMicro) return { verdict: 'warn', rejectReason: '', noticeClass: 'warn' };
  return { verdict: 'ok', rejectReason: '', noticeClass: '' };
}

/**
 * The dearest rate on the card, per token class, with the card's highest
 * multiplier applied. Used ONLY to bound a request whose route is not priced:
 * an unpriced route must be charged too much, never too little.
 *
 * With today's card it resolves to `deepseek-v4-pro` at peak — $1.32 per 1M
 * uncached input and $3.96 per 1M output, 8.8x and 6.6x the flash rate.
 * @param {object} pricing the rate table, defaulting to this package's card
 * @returns {{missPer1M:number,hitPer1M:number,writePer1M:number,outputPer1M:number,provider:string,model:string,multiplier:number}}
 */
function dearestRates(pricing) {
  const card = pricing === undefined ? PRICING : pricing;
  const dearest = { missPer1M: 0, hitPer1M: 0, writePer1M: 0, outputPer1M: 0, provider: '', model: '', multiplier: 1 };
  for (const route of (card === undefined ? [] : card.routes) || []) {
    let multiplier = 1;
    for (const tier of route.tiers || []) if (tier.multiplier > multiplier) multiplier = tier.multiplier;
    for (const key of ['missPer1M', 'hitPer1M', 'writePer1M', 'outputPer1M']) {
      const scaled = (route.rates[key] || 0) * multiplier;
      if (scaled > dearest[key]) {
        dearest[key] = scaled;
        dearest.provider = route.provider;
        dearest.model = (route.models || [])[0] || '';
        dearest.multiplier = multiplier;
      }
    }
  }
  return dearest;
}

/** The route a usage sample was served by, or the deployment default when unnamed. */
function routeOf(message, fallbackRoute) {
  const source = message === undefined || message === null ? undefined : message.source;
  if (source !== undefined && source !== null && typeof source.provider === 'string' && source.provider.length > 0 && typeof source.model === 'string' && source.model.length > 0) {
    return { provider: source.provider, model: source.model, named: true };
  }
  const fallback = fallbackRoute || (PRICING === undefined ? undefined : PRICING.defaultRoute) || { provider: 'deepseek-official', model: 'deepseek-flash' };
  return { provider: fallback.provider, model: fallback.model, named: false };
}

/** One model-facing notice, as a user message the loop admits to the step. */
function notice(text) {
  return { source: { kind: 'user' }, content: [{ type: 'text', text }] };
}

/**
 * Build the guard plugin.
 *
 * A factory, so the guard can be unit-tested and demonstrated against an
 * isolated state directory and an isolated sessions root — without an engine,
 * and without touching the owner's own counters.
 *
 * The mandatory dependency is the price core: `{PRICING, indexRoutes, costOf,
 * normalizeUsage, MICRO, readSessionLog, dshHome}`. `lib/guard.js` passes this
 * package's own sources; a test passes the same ones explicitly, which is what
 * makes the test test the shipped arithmetic.
 *
 * The OPTIONAL dependency is `Schema` — the settings schema class, resolved
 * lazily by the entry (`deps.schemaResolution` carries what the probe did). It is
 * optional because a guard that cannot register a settings namespace must still
 * enforce the ceilings, and because needing it at import time is what made this
 * row fail to load (2026-09-28).
 *
 * @param {object} deps the price core, plus optional I/O and clock overrides
 * @returns {{name:string, apply:Function, decide:Function, resolveLimits:Function, dearestRates:Function, guardState:Function}}
 */
function createGuard(deps = {}) {
  const core = deps.core;
  if (core === undefined || core.PRICING === undefined || core.indexRoutes === undefined || core.costOf === undefined || core.normalizeUsage === undefined || core.MICRO === undefined) {
    throw new Error('spend-guard: the price core is missing, so no cost can be computed. Refusing to construct (pass {core: {PRICING, indexRoutes, costOf, normalizeUsage, MICRO}}).');
  }
  const pricing = core.PRICING;
  const micro = core.MICRO;
  const byKey = core.indexRoutes(pricing);
  const home = deps.dshHome || core.dshHome || dshHome;
  const reader = deps.readSessionLog || core.readSessionLog || readSessionLog;
  const clock = deps.now || (() => Date.now());
  const dearest = dearestRates(pricing);
  const dearestZero = dearest.missPer1M === 0 && dearest.hitPer1M === 0 && dearest.outputPer1M === 0;

  /**
   * What the lazy schema resolution did at mount. `unavailable` is a DEGRADED
   * mode, not a failure: the ceilings still come from the row config and the
   * coded DEFAULTS above. It is reported in the engine log and on disk.
   */
  const schemaInfo =
    deps.schemaResolution === undefined
      ? {
          Schema: deps.Schema,
          mode: deps.Schema === undefined ? 'unavailable' : 'loaded',
          package: '@deepseek-ai/schemastery',
          root: '',
          roots: [],
          attempts: deps.Schema === undefined ? ['none: no resolver was passed to createGuard()'] : [],
        }
      : deps.schemaResolution;

  /** The mounted guard's own state. One per engine; never shared with a test. */
  const state = {
    day: 0,
    micro: 0,
    requests: 0,
    unpriced: 0,
    gaps: [],
    seedRequests: 0,
    seeding: false,
    watermarkMs: 0,
    generating: 0,
    cap: 0,
    lastVerdict: 'ok',
    lastReason: '',
    lastStep: 0,
    reported: '',
    limits: undefined,
    file: '',
    started: false,
    persistError: '',
    healthFile: '',
    healthError: '',
    schemaMode: schemaInfo.mode,
    schemaRoot: schemaInfo.root,
    schemaAttempts: schemaInfo.attempts.slice(),
    mountedAt: '',
    healthWrites: 0,
  };

  /**
   * Move the counter to a new UTC day.
   * @returns {boolean} true when the day actually rolled
   */
  function roll(atMs) {
    const day = utcDayStart(atMs);
    if (day === state.day) return false;
    const rolled = state.day !== 0;
    state.day = day;
    state.micro = 0;
    state.requests = 0;
    state.unpriced = 0;
    state.seedRequests = 0;
    state.gaps = [];
    state.watermarkMs = 0;
    state.reported = '';
    return rolled;
  }

  /**
   * Price one usage sample against the card, exactly, at the event's own instant.
   * A route that is not on the card is BOUNDED at the dearest rate, never
   * treated as free.
   * @returns {{micro:number,priced:boolean,reason:string}}
   */
  function priceSample(usage, route, timeMs) {
    const normalized = core.normalizeUsage(usage, route);
    if (normalized === undefined) return { micro: 0, priced: false, reason: 'the usage sample failed validation, so it cannot be priced' };
    const cost = core.costOf(normalized, byKey, route, timeMs);
    if (cost !== undefined) return { micro: cost.microUsd, priced: true, reason: '' };
    const bound = Math.round(
      (normalized.uncachedInputTokens || 0) * dearest.missPer1M +
        (normalized.cacheReadTokens || 0) * dearest.hitPer1M +
        (normalized.cacheWriteTokens || 0) * dearest.writePer1M +
        (normalized.outputTokens || 0) * dearest.outputPer1M,
    );
    return { micro: bound, priced: false, reason: `${route.provider}/${route.model} is not on the price card, so it was charged at the dearest card rate` };
  }

  /**
   * Add one priced sample to the day. Every path into the counter goes through
   * here, so the live stream and the seed cannot disagree about arithmetic.
   */
  function count(usage, message, timeMs) {
    const route = routeOf(message, pricing.defaultRoute);
    const priced = priceSample(usage, { provider: route.provider, model: route.model }, timeMs);
    state.micro += priced.micro;
    state.requests += 1;
    if (!priced.priced) {
      state.unpriced += 1;
      if (state.gaps.length < 32 && state.gaps.indexOf(priced.reason) === -1) state.gaps.push(priced.reason);
    }
    if (timeMs > state.watermarkMs) state.watermarkMs = timeMs;
    return priced;
  }

  /**
   * Read today's part of the durable logs once, so a restart resumes the day.
   *
   * This is the ONLY scan in the guard and it runs at activation, never per
   * step: a scan of today's logs measured 15.5 s (`docs/mesh/65-spend-guard.md`
   * §1.5), three orders of magnitude too slow to sit in front of a request.
   */
  async function seed(log) {
    const fs = await import('node:fs/promises');
    const readdir = deps.readdir || fs.readdir;
    const stat = deps.stat || fs.stat;
    const limits = state.limits;
    const root = limits.sessionsRoot.length > 0 ? limits.sessionsRoot : join(home(), 'sessions');
    const since = Math.max(state.day, clock() - limits.seedLookbackHours * 3600000);
    let scanned = 0;
    let decoded = 0;
    let unreadable = 0;
    for (const workspace of await readdir(root, { withFileTypes: true })) {
      if (!workspace.isDirectory()) continue;
      for (const session of await readdir(join(root, workspace.name), { withFileTypes: true })) {
        if (!session.isDirectory()) continue;
        const file = join(root, workspace.name, session.name, 'session.v3.jsonl.zstd');
        try {
          const info = await stat(file);
          // Sound pre-filter: logs are append-only and events are chronological,
          // so a log last written before the window holds no event inside it.
          if (info.mtimeMs < since) continue;
          scanned += 1;
          const events = reader(file);
          decoded += 1;
          for (const event of events) {
            if (event === undefined || event.type !== 'assistant/message') continue;
            const at = event.time;
            if (!Number.isFinite(at) || at < state.day || at <= state.watermarkMs) continue;
            const usage = event.data === undefined ? undefined : event.data.usage;
            if (usage === undefined) continue;
            count(usage, event.data.message, at);
            state.seedRequests += 1;
          }
        } catch (error) {
          unreadable += 1;
          if (state.gaps.length < 32) state.gaps.push(`${session.name}: ${error instanceof Error ? error.message : String(error)}`);
        }
      }
    }
    state.seeding = false;
    log(
      `spend-guard: seeded ${state.seedRequests} request(s) from ${decoded}/${scanned} log(s) written since ${new Date(since).toISOString()} ` +
        `(${unreadable} unreadable); day so far $${(state.micro / micro).toFixed(4)} — a LOWER BOUND for this machine, before this engine's own live traffic`,
    );
  }

  /** Read the persisted state, so a restart continues the day instead of resetting it. */
  async function restore(log) {
    try {
      const fs = await import('node:fs/promises');
      const saved = JSON.parse(await fs.readFile(state.file, 'utf8'));
      if (saved === null || typeof saved !== 'object') throw new Error('the state file is not an object');
      state.micro = Number.isFinite(saved.micro) ? saved.micro : 0;
      state.requests = Number.isFinite(saved.requests) ? saved.requests : 0;
      state.unpriced = Number.isFinite(saved.unpriced) ? saved.unpriced : 0;
      state.watermarkMs = Number.isFinite(saved.watermarkMs) ? saved.watermarkMs : 0;
      state.day = Number.isFinite(saved.day) ? saved.day : 0;
      log(`spend-guard: resumed ${state.requests} request(s) / $${(state.micro / micro).toFixed(4)} from ${state.file}`);
    } catch (error) {
      // A missing file is the first run, which is not a fault. Anything else is
      // a gap that must be said out loud, because the day then starts from zero.
      const missing = error !== null && error !== undefined && error.code === 'ENOENT';
      if (!missing) {
        state.gaps.push(`the state file could not be read: ${error instanceof Error ? error.message : String(error)}`);
        log(`spend-guard: WARNING could not read ${state.file} (${error instanceof Error ? error.message : String(error)}); today restarts from the logs and is a LOWER BOUND`);
      }
    }
  }

  /** Write the state. Atomic, and never fatal: the in-memory counter is the truth. */
  function persist(log) {
    const payload = JSON.stringify(
      {
        day: state.day,
        micro: state.micro,
        requests: state.requests,
        unpriced: state.unpriced,
        watermarkMs: state.watermarkMs,
        seedRequests: state.seedRequests,
        lastVerdict: state.lastVerdict,
        lastReason: state.lastReason,
        lastStep: state.lastStep,
        generatingAtLastDecision: state.generating,
        limitsUsd: state.limits === undefined ? undefined : { warn: state.limits.warnUsd, fanout: state.limits.fanoutUsd, ceiling: state.limits.ceilingUsd, concurrencyCap: state.limits.concurrencyCap },
        writtenAt: new Date(clock()).toISOString(),
      },
      null,
      1,
    );
    const write = async () => {
      const fs = await import('node:fs/promises');
      const temp = `${state.file}.tmp`;
      await fs.mkdir(state.file.replace(/[\\/][^\\/]+$/, ''), { recursive: true });
      await fs.writeFile(temp, payload);
      await fs.rename(temp, state.file);
      state.persistError = '';
    };
    write().catch((error) => {
      state.persistError = error instanceof Error ? error.message : String(error);
      log(`spend-guard: WARNING could not persist state to ${state.file}: ${state.persistError}`);
    });
  }

  /**
   * The ACTIVATION RECORD: what this guard is, which mode it mounted in, and
   * which ceilings are in force right now.
   *
   * WHY A FILE AND NOT ONLY A LOG LINE. The engine's own words for an entry that
   * does not activate are one line with no reason, and a plugin that fails to
   * import cannot write anything at all — so the record has to be written by the
   * guard that DID mount, in a place a health check already looks. `<DSH_HOME>/health/`
   * is this deployment's health surface (`plugin-health` writes `processes.json`
   * and `list-agents.json` there, `scripts/engine-vitals.mjs` writes
   * `engine-vitals.json`), and this file is the guard's row in it. A missing or
   * stale `spend-guard.json` on a live engine is itself the finding.
   * @returns {object} the record, as JSON-ready data
   */
  function healthPayload() {
    const limits = state.limits;
    const loaded = state.schemaMode === 'loaded';
    return {
      plugin: 'spend-guard',
      row: 'dsh-plugin-cost/guard',
      mounted: true,
      mountedAt: state.mountedAt,
      writtenAt: new Date(clock()).toISOString(),
      pid: typeof process === 'undefined' ? 0 : process.pid,
      home: home(),
      degraded: !loaded,
      reason: loaded
        ? ''
        : `could not resolve ${schemaInfo.package}, so a "spend-guard:" block in settings.yaml is NOT applied; the row config and the coded DEFAULTS are in force and the ceilings ARE enforced`,
      schema: {
        package: schemaInfo.package,
        mode: state.schemaMode,
        root: state.schemaRoot,
        roots: schemaInfo.roots,
        attempts: state.schemaAttempts,
      },
      limits:
        limits === undefined
          ? {}
          : {
              warnUsd: limits.warnUsd,
              fanoutUsd: limits.fanoutUsd,
              ceilingUsd: limits.ceilingUsd,
              concurrencyCap: limits.concurrencyCap,
              onInternalError: limits.onInternalError,
              source: loaded
                ? 'settings namespace "spend-guard" over the row config over coded DEFAULTS'
                : 'row config over coded DEFAULTS (the settings namespace was NOT registered)',
            },
      counter: {
        day: state.day === 0 ? '' : new Date(state.day).toISOString(),
        usd: Number((state.micro / micro).toFixed(6)),
        requests: state.requests,
        unpriced: state.unpriced,
        seeding: state.seeding,
        lastVerdict: state.lastVerdict,
        lastReason: state.lastReason,
      },
      stateFile: state.file,
      healthWrites: state.healthWrites + 1,
      gaps: state.gaps.slice(0, 8),
    };
  }

  /**
   * Write the activation record. Synchronous, best-effort, never fatal: it exists
   * for a health check that may read it the instant the engine answers, so it
   * cannot be a promise nobody awaited, and the guard's enforcement does not
   * depend on it in any direction.
   * @param {Function} log the guard's info sink
   */
  function writeHealth(log) {
    if (state.healthFile.length === 0) return;
    try {
      mkdirSync(state.healthFile.replace(/[\\/][^\\/]+$/, ''), { recursive: true });
      writeFileSync(state.healthFile, `${JSON.stringify(healthPayload(), null, 2)}\n`);
      state.healthWrites += 1;
      state.healthError = '';
    } catch (error) {
      state.healthError = error instanceof Error ? error.message : String(error);
      const line = `spend-guard: WARNING could not write the activation record to ${state.healthFile}: ${state.healthError}`;
      try {
        log(line);
      } catch {
        // A logger that throws must not turn a reporting failure into an
        // enforcement failure. The ceilings are already in force.
      }
    }
  }

  /** How many agents are generating right now, and whether this step's agent is one of them. */
  function countGenerating(ctx, agent) {
    const agents = typeof ctx.get === 'function' ? ctx.get('agents') : undefined;
    if (agents === undefined || typeof agents.list !== 'function') return { generating: state.generating, available: false, self: true };
    let generating = 0;
    let self = false;
    const selfId = agent === undefined || agent === null || agent.id === undefined ? '' : String(agent.id);
    for (const live of agents.list()) {
      if (live === undefined || live === null || live.status !== 'running') continue;
      generating += 1;
      if (selfId.length > 0 && live.id !== undefined && String(live.id) === selfId) self = true;
    }
    return { generating, available: true, self };
  }

  /**
   * Cordis plugin entry.
   * @param {object} ctx the mounted context
   * @param {object} config the composition row's config, already merged with settings
   */
  function apply(ctx, config = {}) {
    const limits = resolveLimits(config);
    const log = (line) => {
      if (typeof deps.logger === 'function') deps.logger(line);
      else if (ctx.logger !== undefined && typeof ctx.logger.info === 'function') ctx.logger.info(line);
    };
    const warn = (line) => {
      if (typeof deps.logger === 'function') deps.logger(line);
      else if (ctx.logger !== undefined && typeof ctx.logger.warn === 'function') ctx.logger.warn(line);
      else if (ctx.logger !== undefined && typeof ctx.logger.error === 'function') ctx.logger.error(line);
      else if (typeof console !== 'undefined' && typeof console.error === 'function') console.error(line);
    };

    // ── the card first: no card means no enforcement and no pretence ────────
    if (!Array.isArray(pricing.routes) || pricing.routes.length === 0) {
      throw new Error('spend-guard: the price card is missing or holds no routes, so no ceiling can be computed. Refusing to mount rather than enforcing against an assumed zero (the card is packages/plugin-cost/pricing.json).');
    }
    if (dearestZero && !isLimit(config.ceilingUsd)) {
      throw new Error('spend-guard: every rate on the price card is zero, so an unpriced route could not be bounded. Refusing to mount (the card is packages/plugin-cost/pricing.json).');
    }

    state.limits = limits;
    state.cap = limits.concurrencyCap;
    state.file = limits.stateFile.length > 0 ? limits.stateFile : join(home(), 'spend-guard', 'day.json');
    state.healthFile = limits.healthFile.length > 0 ? limits.healthFile : join(home(), 'health', 'spend-guard.json');
    state.mountedAt = new Date(clock()).toISOString();
    state.day = utcDayStart(clock());
    state.seeding = limits.seedFromLogs;

    /**
     * Offer this guard's policy to the settings provider as the `spend-guard`
     * namespace, so `settings/base.yaml` — and any per-machine file — is honoured
     * and the repository stays the single source of truth for the values. If the
     * provider or the schema class is absent, the row's own config stands.
     */
    let source = () => config;
    const settings = typeof ctx.get === 'function' ? ctx.get('settings') : undefined;
    const Schema = deps.Schema;
    if (settings !== undefined && typeof settings.installSection === 'function' && Schema !== undefined) {
      try {
        settings.installSection(ctx, SETTINGS_NAMESPACE, deps.schema === undefined ? policySchema(Schema) : deps.schema, config, {
          setSource: (reader) => {
            source = reader;
          },
          onChange: () => {
            const next = resolveLimits(source());
            const changed =
              state.limits === undefined ||
              next.warnUsd !== state.limits.warnUsd ||
              next.fanoutUsd !== state.limits.fanoutUsd ||
              next.ceilingUsd !== state.limits.ceilingUsd ||
              next.concurrencyCap !== state.limits.concurrencyCap;
            state.limits = next;
            state.cap = next.concurrencyCap;
            if (changed) warn(`spend-guard: limits now warn $${next.warnUsd} / fan-out $${next.fanoutUsd} / ceiling $${next.ceilingUsd}, concurrency cap ${next.concurrencyCap}`);
          },
        });
      } catch (error) {
        warn(`spend-guard: could not register the "${SETTINGS_NAMESPACE}" settings namespace (${error instanceof Error ? error.message : String(error)}); the row config is in force`);
      }
    } else if (settings !== undefined && Schema === undefined) {
      // The entry says this too, and says it with the resolution attempts. Said
      // again here because a caller that builds the guard directly (a test, or a
      // future second entry) must not be able to lose the settings block quietly.
      warn(
        `spend-guard: DEGRADED — the settings provider is mounted but ${schemaInfo.package} is unavailable, so the "${SETTINGS_NAMESPACE}" namespace is NOT registered ` +
          `and a "spend-guard:" block in settings.yaml is IGNORED. The row config and the coded DEFAULTS are in force and the ceilings ARE enforced.`,
      );
    }
    if (limits.unknownKeys.length > 0) warn(`spend-guard: ignoring unknown config key(s): ${limits.unknownKeys.join(', ')}`);

    // ── count: this engine's own traffic, from the live event stream ────────
    ctx.on('session/event', (_session, event) => {
      if (event === undefined || event.type !== 'assistant/message') return;
      const usage = event.data === undefined ? undefined : event.data.usage;
      if (usage === undefined || !Number.isFinite(event.time)) return;
      try {
        // `time` is the event's own write instant, and that instant is what
        // decides peak or off-peak. The watermark excludes anything the seed
        // already counted, so a restart cannot charge the same request twice.
        if (event.time <= state.watermarkMs) return;
        roll(event.time);
        count(usage, event.data.message, event.time);
        persist(log);
      } catch (error) {
        state.gaps.push(`the live count failed: ${error instanceof Error ? error.message : String(error)}`);
        warn(`spend-guard: WARNING could not price a live usage sample (${error instanceof Error ? error.message : String(error)}); today's figure is a LOWER BOUND`);
      }
    });

    // ── enforce: once per step, before anything is billed ───────────────────
    ctx.on('agent/pre-step', async (payload, next) => {
      const step = payload === undefined ? undefined : payload.step;
      const agent = payload === undefined ? undefined : payload.agent;
      let verdict;
      let counts;
      try {
        roll(clock());
        counts = countGenerating(ctx, agent);
        state.generating = counts.generating;
        const live = state.limits === undefined ? limits : state.limits;
        verdict = decide(state.micro, microLimits(live), { generating: counts.generating, cap: state.cap, selfGenerating: counts.self });
      } catch (error) {
        // The guard's own failure is the one case where the policy is explicit.
        if (limits.onInternalError === 'closed') {
          warn(`spend-guard: INTERNAL ERROR, refusing the step because onInternalError is 'closed' (fail closed): ${error instanceof Error ? error.message : String(error)}`);
          return { kind: 'reject' };
        }
        warn(`spend-guard: INTERNAL ERROR, allowing the step because onInternalError is 'open' (fail open): ${error instanceof Error ? error.message : String(error)}`);
        return next();
      }

      const live = state.limits === undefined ? limits : state.limits;
      state.lastStep = Number.isFinite(step) ? step : 0;
      if (verdict.verdict === 'reject') {
        state.lastVerdict = 'reject';
        state.lastReason = verdict.rejectReason;
        state.reported = 'reject';
        const detail =
          verdict.rejectReason === 'daily ceiling'
            ? `daily ceiling reached: $${(state.micro / micro).toFixed(2)} of $${live.ceilingUsd}`
            : `concurrency cap reached: ${counts.generating} agent(s) generating, cap ${state.cap}`;
        warn(`spend-guard: ${detail}; refusing step ${step}. Nothing is billed for the refused step and the turn closes blocked.`);
        persist(log);
        writeHealth(log);
        return { kind: 'reject' };
      }

      const downstream = await next();
      if (downstream === undefined || downstream === null || downstream.kind !== 'enter') return downstream;

      state.lastVerdict = verdict.verdict;
      state.lastReason = verdict.noticeClass;
      // One notice per escalation, not one per step: a notice on every step of a
      // long turn would itself be a cost. A verdict of `ok` re-arms the notice,
      // so dropping back below a threshold and crossing it again says so again.
      if (verdict.verdict === 'ok') state.reported = '';
      if (verdict.verdict === 'ok' || state.reported === verdict.verdict) return downstream;
      state.reported = verdict.verdict;
      const text = [
        `spend-guard: today's DSH spend on this machine is $${(state.micro / micro).toFixed(2)} of a $${live.ceilingUsd} daily ceiling`,
        verdict.noticeClass === 'fanout'
          ? ` — past the $${live.fanoutUsd} fan-out threshold, so start no new subagents or workflows. Work already running continues.`
          : verdict.noticeClass === 'concurrency'
            ? ` — ${counts.generating} agent(s) are generating and the cap is ${state.cap}, so the next new agent will be refused. Start no new fan-out.`
            : ` — past the $${live.warnUsd} warn threshold. The dominant term is re-reading a long session's context: prefer finishing a coherent piece and handing off to a fresh session over continuing this one.`,
        state.seeding ? ' (still seeding today from disk, so this figure is a LOWER BOUND)' : '',
        state.unpriced > 0 ? ` (${state.unpriced} request(s) had no published rate and were charged at the dearest card rate)` : '',
      ].join('');
      warn(text);
      writeHealth(log);
      return { ...downstream, messages: [...downstream.messages, notice(text)] };
    });

    // ── start: restore, seed, then say what is in force ─────────────────────
    log(
      `spend-guard: mounted. warn $${limits.warnUsd} / fan-out $${limits.fanoutUsd} / ceiling $${limits.ceilingUsd} per UTC day, ` +
        `concurrency cap ${limits.concurrencyCap} generating agent(s), fail ${limits.onInternalError}, state ${state.file}, ` +
        `settings schema ${state.schemaMode}${state.schemaRoot === '' ? '' : ` from ${state.schemaRoot}`}, ` +
        `dearest card rate ${dearest.provider}/${dearest.model} at ${dearest.multiplier}x is what bounds an unpriced route`,
    );
    // The activation record goes on disk BEFORE the asynchronous seed, so a health
    // check that reads it the moment the engine answers finds the guard, not its
    // absence. `started` is the async work; `mounted` here is the ceiling.
    writeHealth(log);
    (async () => {
      await restore(log);
      roll(clock());
      if (limits.seedFromLogs) {
        try {
          await seed(log);
        } catch (error) {
          state.seeding = false;
          state.gaps.push(`the seed failed: ${error instanceof Error ? error.message : String(error)}`);
          warn(`spend-guard: could not seed from the session logs (${error instanceof Error ? error.message : String(error)}); today counts this engine's live traffic only and is a LOWER BOUND`);
        }
      } else {
        state.seeding = false;
      }
      state.started = true;
      persist(log);
      writeHealth(log);
    })();
    ctx.effect(() => () => {
      persist(log);
      writeHealth(log);
    });
  }

  return {
    name: 'spend-guard',
    apply,
    decide,
    resolveLimits,
    microLimits,
    utcDayStart,
    dearestRates,
    priceSample,
    /** The live counters, for a test or an operator readout. Never the durable truth. */
    guardState: () => ({ ...state, gaps: state.gaps.slice() }),
  };
}

/**
 * The policy schema, registered with the settings provider so the
 * `spend-guard:` block in `settings.yaml` (merged from `settings/base.yaml`) is
 * validated, and so its UI can render one field per limit.
 * @param {object} Schema the schemastery class, taken from the runtime
 * @returns {object} a schemastery object schema
 */
function policySchema(Schema) {
  const money = (description) => Schema.number().min(0).default(undefined).description(description);
  return Schema.object({
    warnUsd: money('Append a one-line notice to the step at this many USD in a UTC day'),
    fanoutUsd: money('Past this, new subagents and workflows are refused; running work continues'),
    ceilingUsd: money('At this many USD, refuse new billable steps; the turn closes blocked'),
    concurrencyCap: money('Refuse a new generating agent past this many on this machine'),
    onInternalError: Schema.union(['closed', 'open']).description("'closed' refuses the step when the guard itself fails; 'open' allows it"),
    seedFromLogs: Schema.boolean().description('Seed the day once at mount from the durable session logs, which is a lower bound'),
    seedLookbackHours: money('How far back the one seed scan may look'),
    stateFile: Schema.string().description('Empty means <DSH_HOME>/spend-guard/day.json'),
    sessionsRoot: Schema.string().description('Empty means <DSH_HOME>/sessions'),
    healthFile: Schema.string().description('Empty means <DSH_HOME>/health/spend-guard.json — the activation record'),
  });
}

// Test surface, and the source of the mount: everything the guard entry in
// `src/guard-entry.mjs` and the suites in `test/` bind.
export {
  createGuard,
  policySchema,
  decide,
  resolveLimits,
  microLimits,
  utcDayStart,
  dearestRates,
  routeOf,
  notice,
  DEFAULTS,
  KNOWN_KEYS,
  SETTINGS_NAMESPACE,
};
