/**
 * The pure half of the remote transport: build the script that runs on the
 * TARGET node, and parse the bytes that come back.
 *
 * No imports, no I/O, no timers — so this module is unit-testable on its own and
 * the transport module holds nothing but process handling.
 *
 * WHY A FRAME
 * The remote script's stdout carries three kinds of line: a transport-level
 * fact recorded by the *target shell* (which machine actually ran this), the
 * DSH child's own final answer, and the child's exit code. A shell that starts
 * a nested PowerShell can also print a banner, so the answer is fenced between
 * two markers carrying a per-run nonce rather than "everything after line N".
 * The nonce means a child that prints the marker word itself cannot forge or
 * truncate the frame.
 */

/** A marker namespace: `FANOUT_<suffix>_<nonce>`. */
export function markers(nonce = '') {
  const tail = nonce ? `_${nonce}` : '';
  return {
    host: `FANOUT_TRANSPORT_HOST${tail}=`,
    cwd: `FANOUT_TRANSPORT_CWD${tail}=`,
    begin: `FANOUT_BEGIN${tail}`,
    end: `FANOUT_END${tail}`,
    exit: `FANOUT_EXIT${tail}=`,
  };
}

/** Quote one value as a literal PowerShell single-quoted string. */
export function psQuote(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

/** Quote one value as a literal POSIX shell single-quoted word. */
export function shQuote(value) {
  return `'${String(value).replace(/'/g, `'\\''`)}'`;
}

/**
 * The task travels as ONE command-line argument, so a newline in it would be
 * harmless inside a quoted string but is collapsed anyway: `dsh-headless` reads
 * its task from argv and every remote quoting layer is simpler with one line.
 */
export function singleLine(text) {
  return String(text ?? '').replace(/\r/g, ' ').replace(/\n/g, ' ').replace(/\s+/g, ' ').trim();
}

/**
 * The PowerShell program the target runs, delivered with `-EncodedCommand`
 * (base64 UTF-16LE) so no layer ever re-parses the task text.
 *
 * @param spec.nodeExe   absolute path to the target's node interpreter
 * @param spec.dshBin    absolute path to the target's `@deepseek-ai/dsh/lib/bin.js`
 * @param spec.profile   the DSH profile to boot on the target (default `headless`)
 * @param spec.task      the child's prompt
 * @param spec.dshHome   optional DSH_HOME for the child process (isolation)
 * @param spec.cwd       optional working directory for the child
 * @param spec.nonce     frame nonce
 */
export function buildPwshScript({ nodeExe, dshBin, profile, task, dshHome, cwd, nonce = '' }) {
  const m = markers(nonce);
  const lines = [
    '# generated by dsh-plugin-remote-fanout — one remote one-shot subagent turn',
    "$ErrorActionPreference = 'Continue'",
    "$ProgressPreference = 'SilentlyContinue'",
  ];
  if (dshHome) lines.push(`$env:DSH_HOME = ${psQuote(dshHome)}`);
  if (cwd) lines.push(`Set-Location -LiteralPath ${psQuote(cwd)}`);
  lines.push(
    `[Console]::Out.WriteLine(${psQuote(m.host)} + $env:COMPUTERNAME)`,
    `[Console]::Out.WriteLine(${psQuote(m.cwd)} + (Get-Location).Path)`,
    `[Console]::Out.WriteLine(${psQuote(m.begin)})`,
    `& ${psQuote(nodeExe)} ${psQuote(dshBin)} --profile ${psQuote(profile)} ${psQuote(singleLine(task))}`,
    '$fanoutExit = $LASTEXITCODE',
    `[Console]::Out.WriteLine(${psQuote(m.end)})`,
    `[Console]::Out.WriteLine(${psQuote(m.exit)} + $fanoutExit)`,
    // `[Environment]::Exit` rather than `exit`: PowerShell's own exit path waits
    // on teardown after a native child has run, and on Windows that wait can
    // outlive the work (measured 2026-09-17: the frame closes, the answer is
    // written, and the ssh session stays open until the client's own timeout).
    // The transport settles on the frame, so this is belt and braces.
    '[Environment]::Exit($fanoutExit)',
  );
  return lines.join('\n');
}

/**
 * The POSIX twin, for a Linux/macOS worker node. Delivered on stdin to `sh -s`
 * so the task text never reaches an argument-parsing layer either.
 */
export function buildPosixScript({ nodeExe, dshBin, profile, task, dshHome, cwd, nonce = '' }) {
  const m = markers(nonce);
  const lines = ['# generated by dsh-plugin-remote-fanout — one remote one-shot subagent turn'];
  if (dshHome) lines.push(`export DSH_HOME=${shQuote(dshHome)}`);
  if (cwd) lines.push(`cd ${shQuote(cwd)}`);
  lines.push(
    `printf '%s\\n' "${m.host}$(hostname)"`,
    `printf '%s\\n' "${m.cwd}$(pwd)"`,
    `printf '%s\\n' "${m.begin}"`,
    `${shQuote(nodeExe)} ${shQuote(dshBin)} --profile ${shQuote(profile)} ${shQuote(singleLine(task))}`,
    'fanout_exit=$?',
    `printf '%s\\n' "${m.end}"`,
    `printf '%s\\n' "${m.exit}$fanout_exit"`,
    'exit $fanout_exit',
  );
  return lines.join('\n');
}

/**
 * Read the framed result out of the remote stdout.
 *
 * `answer` is the child's own final assistant message, exactly as
 * `dsh --profile headless` prints it. `host` and `cwd` are facts recorded by
 * the TARGET's shell before the child ran — they are the transport's own
 * evidence of where the turn happened, independent of anything the model wrote.
 */
export function parseFanout(stdout, nonce = '') {
  const m = markers(nonce);
  const text = String(stdout ?? '');
  const lines = text.split(/\r?\n/);
  let host;
  let cwd;
  let exitCode;
  let beginAt = -1;
  let endAt = -1;
  for (let i = 0; i < lines.length; i += 1) {
    const line = lines[i].trim();
    if (line.startsWith(m.host)) host = line.slice(m.host.length).trim();
    else if (line.startsWith(m.cwd)) cwd = line.slice(m.cwd.length).trim();
    else if (line === m.begin) beginAt = i;
    else if (line === m.end && beginAt >= 0) endAt = i;
    else if (line.startsWith(m.exit)) {
      const parsed = Number.parseInt(line.slice(m.exit.length).trim(), 10);
      if (Number.isFinite(parsed)) exitCode = parsed;
    }
  }
  const framed = beginAt >= 0 && endAt > beginAt;
  return {
    host,
    cwd,
    exitCode,
    framed,
    answer: framed ? lines.slice(beginAt + 1, endAt).join('\n').trim() : '',
  };
}
