<#
.SYNOPSIS
  Stop scheduled-task PowerShell/python/cmd console windows from popping up and
  stealing focus, by routing each task's command through a per-task wscript launcher
  that creates the process with SW_HIDE. That hides the console at creation time, so
  there is no flash and no focus steal (unlike `-WindowStyle Hidden`, which hides the
  window only AFTER it has been created and shown).

.DESCRIPTION
  Why wscript and not `-WindowStyle Hidden`:
    An Interactive scheduled task that runs pwsh.exe/powershell.exe/python.exe/cmd.exe
    allocates a visible console and, for the DSH Engine Watchdog, was observed popping a
    window every minute despite already carrying `-WindowStyle Hidden`. PowerShell applies
    WindowStyle after the console host has shown the window, so a flash (and, with Task
    Scheduler's activation, a focus steal) still happens. `WScript.Shell.Run cmd, 0, True`
    passes SW_HIDE in STARTUPINFO, so the console is never shown at all.

  It preserves everything else: same LogonType, same RunLevel, same triggers, same
  ExecutionTimeLimit, same working directory, and the launcher waits for the command and
  returns its exit code, so Task Scheduler's "Last Run Result" stays truthful and
  MultipleInstances/ExecutionTimeLimit behave exactly as before.

  Each converted task gets two files in -WrapperDir:
    <safe-name>.vbs  - the launcher (SW_HIDE, wait, propagate exit code)
    <safe-name>.json - the original action, so -Restore is exact

  The conversion is idempotent: a task whose action already points at a wscript/cscript
  launcher is left alone.

.EXAMPLE
  pwsh -File scripts\Set-TaskHidden.ps1 -WhatIf              # preview every change
  pwsh -File scripts\Set-TaskHidden.ps1                      # convert all interactive console tasks
  pwsh -File scripts\Set-TaskHidden.ps1 -Only 'PersonalSecretary-NodeAgent'
  pwsh -File scripts\Set-TaskHidden.ps1 -Restore -Only 'PersonalSecretary-NodeAgent'
#>
[CmdletBinding()]
param(
    [string]$WrapperDir = (Join-Path $PSScriptRoot 'hidden-tasks'),
    [string[]]$Only = @(),
    [switch]$Restore,
    [switch]$WhatIf
)

$ErrorActionPreference = 'Stop'
$WSCRIPT = Join-Path $env:SystemRoot 'System32\wscript.exe'

function Get-ExeName([string]$exe) {
    if (-not $exe) { return '' }
    return ([System.IO.Path]::GetFileName($exe)).ToLowerInvariant()
}

# Does this action launch something that gets a visible console window when run interactively?
# Covers .exe console hosts, extensionless names (a task may say `cmd` or `python`), and
# .cmd/.bat scripts — all of which pop a window and steal focus. wscript.exe is our own
# hidden launcher, so a task already pointing at it is excluded (keeps the job idempotent).
function Test-IsConsoleAction([string]$exe) {
    if (-not $exe) { return $false }
    $name = Get-ExeName $exe
    if ($name -eq 'wscript.exe') { return $false }
    if ($name -match '\.(cmd|bat|com)$') { return $true }
    $base = $name -replace '\.exe$', ''
    return ($base -in @('pwsh', 'powershell', 'python', 'py', 'cmd', 'node', 'conhost', 'cscript'))
}

function Get-SafeName([string]$taskName) {
    return ($taskName -replace '[^\w\-]', '_')
}

# Reconstruct the command line Task Scheduler would have run.
function Build-CommandLine($action) {
    if ($action.Arguments) {
        return '"{0}" {1}' -f $action.Execute, $action.Arguments
    }
    return '"{0}"' -f $action.Execute
}

function New-LauncherVbs([string]$cmd, [string]$workDir) {
    $esc = $cmd.Replace('"', '""')
    $lines = @(
        "' Generated by Set-TaskHidden.ps1 - do not edit by hand.",
        "' Launches the command with SW_HIDE (no console, no flash), waits, and returns",
        "' its exit code so Task Scheduler Last Run Result / limits behave as before.",
        'Set sh = CreateObject("WScript.Shell")'
    )
    if ($workDir) {
        $wdEsc = $workDir.Replace('"', '""')
        $lines += "sh.CurrentDirectory = `"$wdEsc`""
    }
    $lines += "WScript.Quit sh.Run(`"$esc`", 0, True)"
    return ($lines -join "`r`n") + "`r`n"
}

function Write-LauncherFiles([string]$taskName, $action) {
    New-Item -ItemType Directory -Force -Path $WrapperDir | Out-Null
    $safe = Get-SafeName $taskName
    $vbs = Join-Path $WrapperDir "$safe.vbs"
    $json = Join-Path $WrapperDir "$safe.json"
    $cmd = Build-CommandLine $action
    $manifest = [ordered]@{
        taskName        = $taskName
        execute         = $action.Execute
        arguments       = $action.Arguments
        workingDirectory = $action.WorkingDirectory
        commandLine     = $cmd
    }
    $content = New-LauncherVbs $cmd $action.WorkingDirectory
    [System.IO.File]::WriteAllText($vbs, $content, (New-Object System.Text.UTF8Encoding($false)))
    $manifestJson = $manifest | ConvertTo-Json
    [System.IO.File]::WriteAllText($json, $manifestJson, (New-Object System.Text.UTF8Encoding($false)))
    return $vbs
}

function New-WscriptAction([string]$vbsPath) {
    return New-ScheduledTaskAction -Execute $WSCRIPT -Argument ('//B //NoLogo "{0}"' -f $vbsPath)
}

# ── discover the tasks we care about ─────────────────────────────────────────
$all = Get-ScheduledTask | Where-Object { $_.State -ne 'Disabled' }
$targets = @()
foreach ($t in $all) {
    if ($Only.Count -gt 0 -and $t.TaskName -notin $Only) { continue }
    $isInteractive = ($t.Principal.LogonType -eq 'Interactive')
    if (-not $isInteractive) { continue }
    $acts = @($t.Actions)
    if ($acts.Count -eq 0) { continue }
    # Single-action tasks only; multi-action tasks are left alone (rare and need per-action care).
    if ($acts.Count -gt 1) { continue }
    $a = $acts[0]
    $exeName = Get-ExeName $a.Execute
    $isWrapped = ($exeName -eq 'wscript.exe')
    if ($Restore) {
        if ($isWrapped) { $targets += $t }
        continue
    }
    if (Test-IsConsoleAction $a.Execute) { $targets += $t }
}

if ($targets.Count -eq 0) {
    Write-Host 'No matching interactive console tasks found.'
    exit 0
}

# ── apply ────────────────────────────────────────────────────────────────────
foreach ($t in $targets) {
    $name = $t.TaskName
    if ($Restore) {
        $safe = Get-SafeName $name
        $json = Join-Path $WrapperDir "$safe.json"
        if (-not (Test-Path $json)) {
            Write-Warning "no manifest for '$name' at $json - cannot restore"
            continue
        }
        $m = Get-Content -Raw -LiteralPath $json | ConvertFrom-Json
        $action = New-ScheduledTaskAction -Execute $m.execute -Argument $m.arguments -WorkingDirectory $m.workingDirectory
        if ($WhatIf) {
            Write-Host ("[restore] {0} -> {1} {2}" -f $name, $m.execute, $m.arguments)
            continue
        }
        Set-ScheduledTask -TaskName $name -Action $action | Out-Null
        Write-Host ("[restored] {0}" -f $name) -ForegroundColor Green
        continue
    }

    $a = $t.Actions[0]
    $cmd = Build-CommandLine $a
    $vbs = Write-LauncherFiles $name $a
    if ($WhatIf) {
        Write-Host ("[hide] {0} -> {1} {2}" -f $name, $WSCRIPT, ('//B //NoLogo "{0}"' -f $vbs))
        Write-Host ("       runs: {0}" -f $cmd)
        continue
    }
    $action = New-WscriptAction $vbs
    try {
        Set-ScheduledTask -TaskName $name -Action $action | Out-Null
        # Verify it took.
        $check = Get-ScheduledTask -TaskName $name
        $checkExe = Get-ExeName $check.Actions[0].Execute
        if ($checkExe -eq 'wscript.exe') {
            Write-Host ("[hidden]  {0}" -f $name) -ForegroundColor Green
        } else {
            Write-Warning ("[UNCHANGED] {0} still runs {1}" -f $name, $check.Actions[0].Execute)
        }
    } catch {
        Write-Warning ("[FAILED] {0}: {1}" -f $name, $_.Exception.Message)
    }
}
